---
- hosts: [build]
  become: yes
  tasks:
    - name: Build an image 1 and push it to docker hub 
      docker_image:
        path: ./apps/v1.0.0
        name: yeganx/blue
        tag: 1.0
        state: present
        push: yes
      ignore_errors: yes
    - name: Build an image 2 and push it to docker hub
      docker_image:
        path: ./apps/v2.0.0
        name: yeganx/blue
        tag: 2.0
        state: build
        push: yes
      ignore_errors: yes
    - name: Build an image 3 and push it to docker hub
      docker_image:
        path: ./apps/v3.0.0
        name: yeganx/blue
        tag: 3.0
        state: build
        push: yes
      ignore_errors: yes
    - name: Build an image 4 and push it to docker hub
      docker_image:
        path: ./apps/v4.0.0
        name: yeganx/blue
        state: build
        tag: 4.0
        push: yes
      ignore_errors: yes

